image: node:lts
pages:
  stage: deploy
  cache:
    key:
      files:
        - theratype/package-lock.json
      prefix: npm
    paths:
      - theratype/node_modules/
  script:
    - cd theratype
    - npm install
    - npm run build
    - cd ..
    - mkdir -p public
    - cp -a theratype/dist/. public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
